export class ChatActions {
    static ASSIGNED_USERNAME = 'ASSIGNED_USERNAME'
    static GET_ONE = 'GET_ONE'
    static PITCH_IN = 'PITCH_IN'
    static ANOTHER_ONE_PITCHED_IN = 'ANOTHER_ONE_PITCHED_IN'
    static PUT_ALL_NAMES_TO_REDUCER = 'PUT_ALL_NAMES_TO_REDUCER'
    static DELIVER_UPDATED_POT_TO_REDUCER = 'DELIVER_UPDATED_POT_TO_REDUCER'
    static CURRENT_POT_TO_REDUCER = 'CURRENT_POT_TO_REDUCER'
}